### ISSUE TITLE
Undefined class NativeLibrary, can't understand how this should work

### ISSUE THREAD

**Issue by benkuper** [featherbear/flutter-ndi#1]
Hello,
I would really like to use this but there are a lot of holes in the documentation on the way to use it :)
- Is this repo a full project that can run as standalone (after ffigen) or is it just the lib generation ?
- If it's not the full project, what action is needed after ffigen, which files to copy to my actual project ?
- It seems that NativeLibrary is not (or not anymore) a defined class in FFI, I couldn't understand how to be able to use it. Is this a version problem or am I missing something ?

Thank you very much

**Comment by featherbear** [comment]
Hey @benkuper 

This repo only produces the FFI bindings, and has no standalone ability to run.
The files should then be references as a dependency within the `pubspec.yaml` file

---

Have a look at this project to see how to integrate the bindings - https://github.com/featherbear/aNDI

https://github.com/featherbear/aNDI/blob/7741e419675a4f109c344125a5f0cfd0bb5aa3e4/pubspec.yaml#L27-L28

For that project specifically, it requires the bindings to be in an adjacent directory, so you'll want the folder structure to be

```
|
+-- flutter-ndi
|  +--- android
|  +--- ios
|  +--- lib
|  +--- test
|  \--- ...
+-- aNDI
|  +--- android
|  +--- ios
|  +--- lib
|  +--- test
|  \--- ...
```

---

> It seems that NativeLibrary is not (or not anymore) a defined class in FFI, I couldn't understand how to be able to use it. Is this a version problem or am I missing something?

`NativeLibrary` is defined in the generated output file

![image](https://user-images.githubusercontent.com/1159091/186512670-43946d20-3917-4283-bf84-3a5473f72970.png)



For reference, I used the following versions

```
λ flutter --version
Flutter 2.5.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 3595343e20 (11 months ago) • 2021-09-30 12:58:18 -0700
Engine • revision 6ac856380f
Tools • Dart 2.14.3
```

**Comment by benkuper** [comment]
ah thank you, makes sense :) would be interesting to backlink aNDI in the flutter-ndi readme for people to understand how to integrate it (or maybe i'm alone in this mess)

the libndi_bindings.dart is empty after generation, not sure why...

Here is my full flutter doctor log 

```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.795], locale en-US)
    • Flutter version 3.0.5 at D:\Softwares\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\bkupe\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = C:\Users\bkupe\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32819.101
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.70.2)
    • VS Code at C:\Users\bkupe\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.795]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.63

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found
```

**Comment by benkuper** [comment]
Ah !
found the culprit :)
I was indeed not testing the advanced sdk, but your pubspec.yaml is already pointing to the Advanced header, though the header files are not in the repo.
Copying the advanced header files allowed me to generate the NDI and ffigen runs just fine. I guess reverting to including the basic NDI would work as well. thank you :)

BTW, if you're looking for NDI implementations in advanced usage (maybe optimized as well), I found this repo. I was about to get their implementation because I couldn't run yours. Now I can actually compare and see :)

https://github.com/MindStudioOfficial/ndiscopes

**Comment by featherbear** [comment]
Ah awesome!

Thanks for sharing that other project! Looks like they source the standard header files... makes me wonder why I changed to the advanced SDK headers... 🤷‍♀️
